### ISSUE TITLE
Missing information in documentation about shouldAdvanceTime

### ISSUE THREAD

**Issue by stefanschenk** [sinonjs/fake-timers#390]
-   FakeTimers version : 6.0.1

I am using fake-timers for some time now and I wanted to utilize the `shouldAdvanceTime` option. 
But I did not get it to work from the start.

This was my install code;
```
const installFakeClock = (): void => {
  (window as any).fakeClock = install({
    now: new Date(),
    toFake: ['setTimeout', 'clearTimeout'],
    shouldAdvanceTime: true,
  });
};
```

According to the documentation, this should work. Set `shouldAdvanceTime` to true and it will use the default time delta of 20ms. However, it would not work. The fake timer was not advancing automatically.

I had to look through the source to see that it actually also expects `setInterval` and `clearInterval` to be faked too.

I'm not sure why the advanceTime needs set and clearInterval to be faked too, but it was not expected. 
If it is needed, could you change the documentation to reflect that the `setInterval` and `clearInterval` are needed for this option to work?

**Comment by fatso83** [comment]
Spent some time looking into this to understand what was going on. You probably can too, btw, as this entire project is just 1600 lines in total, and is very easy to understand. I merged this feature 4 years ago in https://github.com/sinonjs/fake-timers/commit/3775a00bf1cc91acc11a195a24b35cf14ab1217d, but I never really used it myself, so I was a bit unfamiliar with it and have long since forgotten how it is implemented, but you are indeed right in that it [implicitly relies on stubbing setInterval](https://github.com/sinonjs/fake-timers/commit/3775a00bf1cc91acc11a195a24b35cf14ab1217d#diff-3c453e87acf43f6d28cb538a6102bc444c612b188b408f7f3028b2df00f1dc93R674-R680). 

I am not totally sure _why_, though, as it seems like it only calls through to the real/original version, so the `clock.methods[i] === "setInterval"` bit should be possible to remove without affecting the functionality. Will have a go at this.

**Comment by fatso83** [comment]
Fix in place. PR coming up

**Comment by fatso83** [comment]
See if #391 does not fix your issue. 
- clone this project
- run `npm install && npm link`
- In your own project, do `npm link @sinonjs/fake-timers`

**Comment by fatso83** [comment]
Did not hear back, but this should make the actual implementation be in line with the docs, so no doc update needed 😄

**Comment by stefanschenk** [comment]
@fatso83 Thanks for looking into it and creating a PR in such short time.
